"""Add playback_type column to playback_activity

Revision ID: b3fc29797264
Revises: b4dc7397847b
Create Date: 2026-05-10 00:12:48.984219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3fc29797264'
down_revision: Union[str, Sequence[str], None] = 'b4dc7397847b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playback_activity', sa.Column('playback_type', sa.String(length=64), nullable=True))
    op.create_index('idx_playback_type', 'playback_activity', ['playback_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_playback_type', table_name='playback_activity')
    op.drop_column('playback_activity', 'playback_type')
    # ### end Alembic commands ###
