"""Add audio_codec column to Item table

Revision ID: b4dc7397847b
Revises: 9604db89ffb5
Create Date: 2026-05-08 22:29:59.531165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4dc7397847b'
down_revision: Union[str, Sequence[str], None] = '9604db89ffb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('audio_codec', sa.String(length=64), nullable=True))
    op.drop_index(op.f('idx_languages'), table_name='items')
    op.create_index('idx_audio_codec', 'items', ['audio_codec'], unique=False)
    op.drop_column('items', 'languages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('languages', sa.TEXT(), nullable=True))
    op.drop_index('idx_audio_codec', table_name='items')
    op.create_index(op.f('idx_languages'), 'items', ['languages'], unique=False)
    op.drop_column('items', 'audio_codec')
    # ### end Alembic commands ###
